---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: certbot
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certbot
subjects:
- kind: ServiceAccount
  name: certbot
  namespace: default
roleRef:
  kind: Role
  name: certbot
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot-renewal
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: certbot
          restartPolicy: OnFailure
          containers:
          - name: certbot
            image: curlimages/curl:latest
            command:
              - /bin/sh
              - -c
            args:
              - |
                set -ex
                # Download the artifact from GitHub Actions (public repo)
                curl -L "https://api.github.com/repos/OpScaleHub/kind/actions/artifacts" | \
                  jq -r ".artifacts[] | select(.name==\"${ARTIFACT_NAME}\") | .archive_download_url" | \
                  xargs -I {} curl -L -o artifact.zip {}

                # Extract the artifact
                apk add unzip
                unzip artifact.zip -d /tmp/artifact

                # Apply the certificate as a Kubernetes secret
                kubectl -n default create secret generic wildcard-tls-secret \
                  --from-file=tls.crt=/tmp/artifact/fullchain.pem \
                  --from-file=tls.key=/tmp/artifact/privkey.pem \
                  --dry-run=client -o yaml | kubectl apply -f -

                echo "Certificate downloaded and secret updated."
            volumeMounts:
            - name: artifact-data
              mountPath: /tmp/artifact
          volumes:
          - name: artifact-data
            emptyDir: {}
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 8.8.8.8
              - 1.1.1.1
